### ISSUE TITLE
Support specialized compression codecs please

### ISSUE THREAD

**Issue by AbstractiveNord** [julianbuettner/swapvec#10]
It's great to support special compression codecs, such as Delta, DoubleDelta, Gorilla, FPC, T64.

**Comment by julianbuettner** [comment]
Hi there.

I never heard of any of those algorithms and they are bearly googlable.  
Also there seem to be no available good rust crates and implementing them myself would be out of scope.
So I am afraid I am going to close this issue.  
If you feel this is wrong, feel free to re-open it, maybe with a reasoning why it is a good idea to add the specific niche compression algortihm.

As noted on the other issue, I added the possibility to inject your own compression algorithm.
See [here](https://docs.rs/swapvec/0.3.0/swapvec/trait.Compress.html) and [here](https://docs.rs/swapvec/0.3.0/swapvec/index.html).
