### ISSUE TITLE
Support TTL please

### ISSUE THREAD

**Issue by AbstractiveNord** [julianbuettner/swapvec#12]
Support Time-To-Live feature.

**Comment by julianbuettner** [comment]
What exactly do you mean? How would you like the vector/stored data/file to behave?

**Comment by AbstractiveNord** [comment]
It's about periodical trimming tail of vector, based on timestamp.

**Comment by julianbuettner** [comment]
This would require more of a ringbuffer like data structure. I am affraid that is a profoundly different problem you want to get solved.

However, you could use my related project [DiskAlloc] (https://github.com/julianbuettner/diskallocator) and insert items with a timestamp in a disk allocated VecDequeue and periodically purge the front items. You can use this allocator for VecDequeue as well as for vectors:

[VecDequeue with allocator] (https://doc.rust-lang.org/stable/std/collections/struct.VecDeque.html#method.new_in)

Read the readme carefully and check if it might solve your problem.
