### ISSUE TITLE
Build error on linux

### ISSUE THREAD

**Issue by Almeida-a** [julianbuettner/swapvec#4]
Hello! Perhaps similarly to #2 , the project now does not seem to be correctly building on linux.
 
The `cargo build` output is as follows:
```
error[E0432]: unresolved import `std::os::fd::AsRawFd`
  --> src/swapvec.rs:10:5
   |
10 | use std::os::fd::AsRawFd;
   |     ^^^^^^^^^^^^^^^^^^^^ no `AsRawFd` in `os::fd`

error[E0603]: module `fd` is private
   --> src/swapvec.rs:10:14
    |
10  | use std::os::fd::AsRawFd;
    |              ^^ private module
    |
note: the module `fd` is defined here
   --> ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/os/mod.rs:150:1
    |
150 | mod fd;
    | ^^^^^^

error[E0599]: no method named `as_raw_fd` found for struct `File` in the current scope
   --> src/swapvec.rs:132:69
    |
132 |         let file_descriptor = self.tempfile.as_ref().map(|x| x.file.as_raw_fd());
    |                                                                     ^^^^^^^^^ method not found in `File`
    |
   ::: ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/os/fd/raw.rs:57:8
    |
57  |     fn as_raw_fd(&self) -> RawFd;
    |        --------- the method is available for `File` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   | use std::os::unix::io::AsRawFd;
    |

Some errors have detailed explanations: E0432, E0599, E0603.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `swapvec` due to 3 previous errors

```

**Comment by rgret-dev** [comment]
What OS are you using?

**Comment by rgret-dev** [comment]
Sidenote: The official docs suggest a slightly different compilation config [here](https://doc.rust-lang.org/std/os/fd/trait.AsRawFd.html#required-methods) when using `std::os::fd::AsRawFd`.
```
#[cfg(any(unix, target_os = "wasi"))]
```
I can submit a PR to change this after this issue is figured out.

**Comment by julianbuettner** [comment]
Thanks for opening a request. I could not reproduce as well on WSL, but I applied the change suggested by rmg-x.  
Could you please try to compile/test again?  
If it does not work, please re-open this issue.

Thank you!

**Comment by rgret-dev** [comment]
> but I applied the change suggested

Cool, thanks! I did notice that the cfg for the import wasn't updated, just the usage of the method.

**Comment by Almeida-a** [comment]
Thank you for your time resolving this issue!
Unfortunately, your fix was unsuccessful as the same error still appears.

I'm just speculating, but it may have been because you didn't apply your fix `#[cfg(not(any(unix, target_os = "wasi")))]` to the import  where the error is: `use std::os::fd::AsRawFd;`, as @rmg-x pointed out.

Edit: @julianbuettner I think only you have permission to reopen this issue.
